experiment:
  benchmarks:
    - disqco.mfpqc.qaoa
    - disqco.mfpqc.qft
    - disqco.mfpqc.qv
    - disqco.mfpqc.cp_large
    - disqco.mfpqc.cp_scaling
    - qasmbench.small
  network:
    topologies:
      - linear
    num_qpus:
      - 2
      - 4
  partitioners:
    - mlfm-r
    - fgp-roee
    - pytket-dqc-p
    - pytket-dqc-pe
    - pytket-dqc-esd
  metrics: null
  custom_metrics:
    - ebit_count
  exec_time_columns:
    - preprocessing_exec_time_s
    - partition_exec_time_s
    - postprocessing_exec_time_s
  timeout_seconds: 600
  skip_larger_circuits_after_timeout: 1
results:
  output_dir: results
  name: ""
  description: ""
